// Timelines for the gig video (seconds). shots = background clips, cues = things that happen.
export const FPS = 30;
export const TIMELINES = {};

const UNBOX_ITEMS = [
  { name: '3D models', sub: 'characters, props, whole worlds', art: 'dragon', rarity: 3 },
  { name: 'Animated characters', sub: 'they walk, talk, dance, roar', art: 'fox', rarity: 4 },
  { name: '2D pixel art', sub: 'sprites, icons, UI', art: 'heart', rarity: 2 },
  { name: 'Sound effects + music', sub: 'made for your game', art: 'speaker', rarity: 2 },
  { name: 'Full source code', sub: 'JavaScript + Three.js, yours', art: 'brackets', rarity: 3 },
];
// ------------------------------------------------------------------ the gig video (74 s)
const W = 'blocks';
const TIER_FEATS = (days, lv, pl, rev) => [`${days}-day delivery`, `${lv} level${lv > 1 ? 's' : ''}`, `${pl} plugin${pl > 1 ? 's' : ''}`, 'design + animation', 'source code included', `${rev} revision${rev > 1 ? 's' : ''}`];
const BADGE = (at, text, sub, color = '#ffd05a') => ({ at, fx: { kind: 'tag', text, sub, x: 1110, y: 92, w: 250, h: 104, big: 44, color, rot: 4, seed: 4, life: 3.6, sound: 'reveal_rare' } });
const JAR0 = 17.6;
TIMELINES.main = {
  length: 74.4,
  file: 'pukking-gig-video',
  mix: { music: 0.9, sfx: 1.1, voice: 1.7 },
  shots: [
    { clip: 'tb_gag', at: 0, dur: 4.4, from: 39, frames: 180, sound: true },
    { clip: 'tb_wake', at: 4.4, dur: 7.8, from: 6, frames: 300, zoom: [1.15, 1.15], sound: true, anchors: true },
    { clip: 'tb_globe', at: 12.2, dur: 5.4, frames: 165 },
    { clip: 'tb_jar', at: JAR0, dur: 5.0, frames: 150 },
    { clip: 'tb_tiers3', at: 22.6, dur: 9.0, frames: 270 },
    { clip: 'tb_extras3', at: 31.6, dur: 5.0, frames: 150 },
    { clip: 'tb_wyg', at: 36.6, dur: 10.4, frames: 300 },
    { clip: 'shore', at: 47.0, dur: 4.0, frames: 90, speed: 0.75, zoom: [1.04, 1.12] },
    { clip: 'mudkip', at: 51.0, dur: 4.4, frames: 93, speed: 0.7, zoom: [1.0, 1.08] },
    { clip: 'tb_bears', at: 55.4, dur: 3.5, from: 0, frames: 480, sound: 0.6 },
    { clip: 'tb_bears', at: 58.9, dur: 2.7, from: 352, frames: 480, sound: 0.6 },
    { clip: 'dv_ride', at: 61.6, dur: 2.8, from: 4, frames: 100 },
    { clip: 'dv_wheelie', at: 64.4, dur: 2.5, from: 12, frames: 90 },
    { clip: 'dv_title', at: 66.9, dur: 1.7, from: 112, frames: 180, zoom: [1.22, 1.3], pan: [[0.5, 0.9], [0.5, 0.9]] },
    { clip: 'tb_lineup', at: 68.6, dur: 5.8, from: 0, frames: 210, speed: 0.8, anchors: true },
  ],
  cues: [
    // ---- cold open + hello
    { at: 0, music: 'title', volume: 0.55 },
    { at: 0.3, fx: { kind: 'sign', l1: 'PUKKING', l2: 'GAME DEV', scale: 1.3 } },
    { at: 3.95, wipe: 'iris', sfx: 'iris', volume: 0.5 },
    { at: 4.3, fx: { kind: 'unsign' } },
    { at: 4.4, music: 'morning', fade: 0.8, volume: 0.5 },
    { at: 5.05, say: 'GAH! what time is it?!', x: 420, y: 170, bubble: 'shout', dur: 1.7 },
    { at: 7.25, say: "wait... we're recording?!", anchor: 'fox', bubble: 'scared', dur: 1.9 },
    { at: 9.8, say: "oh hi! i'm Pukking!", x: 640, y: 250, bubble: 'excited', dur: 2.0 },
    { at: 11.75, wipe: W, sfx: 'whoosh', volume: 0.45 },
    // ---- my story: the globe, the coin jar
    { at: 12.4, notify: "i live in Vancouver, Canada... but i'm from Thailand!", mood: 'happy', dur: 3.0 },
    { at: 12.45, sfx: 'pop_in', volume: 0.5 }, { at: 13.1, sfx: 'whoosh', volume: 0.45, pitch: 0.8 }, { at: 15.1, sfx: 'whoosh', volume: 0.35, pitch: 1.2 }, { at: 16.15, sfx: 'levelup', volume: 0.5 },
    { at: 12.6, fx: { kind: 'label', text: 'Thailand  →  Vancouver', x: 40, y: 40, life: 4.6, tape: 'blue' } },
    { at: 15.5, notify: "i've made games and art since i was a kid.", mood: 'happy', dur: 2.0 },
    { at: 17.15, wipe: 'iris', sfx: 'iris', volume: 0.45 },
    ...Array.from({ length: 18 }, (_, k) => ({ at: JAR0 + 0.63 + k * 0.2, sfx: 'coin', volume: 0.3, pitch: 1 + (k % 5) * 0.05 })),
    { at: 17.8, notify: "your orders help me study abroad + pay rent. love y'all!", mood: 'excited', bubble: 'excited', dur: 3.4 },
    { at: 20.9, sfx: 'heart', volume: 0.5 },
    { at: 22.15, wipe: W, sfx: 'whoosh', volume: 0.45 },
    // ---- tiers
    { at: 22.6, music: 'rush', fade: 0.4, volume: 0.42 },
    { at: 22.7, fx: { kind: 'title', text: 'PICK YOUR TIER', x: 200, y: 40, size: 41.67, out: 4, life: 8.4, rot: -3, sound: 'fanfare_small' } },
    { at: 22.9, fx: { kind: 'tier', x: 222, y: 488, w: 380, scale: 0.86, name: 'DUCK TIER', level: 'BASIC', price: '$75', days: '3-day delivery', color: '#3aa8e0', dark: '#1a6aa0', seed: 21, rot: -1.2, life: 8.6,
      desc: 'a prototype 3D JavaScript mini game: the main mechanic + custom assets', feats: TIER_FEATS(3, 1, 1, 1) } },
    { at: 23.3, fx: { kind: 'tier', x: 640, y: 488, w: 380, scale: 0.86, name: 'FOX TIER', level: 'STANDARD', price: '$150', days: '5-day delivery', color: '#ff8a2a', dark: '#c0501a', seed: 22, life: 8.2,
      desc: 'a detailed 3D JavaScript game with custom systems, characters and art', feats: TIER_FEATS(5, 2, 2, 2) } },
    { at: 23.7, fx: { kind: 'tier', x: 1058, y: 488, w: 380, scale: 0.86, name: 'BEAR TIER', level: 'PREMIUM', price: '$350', days: '10-day delivery', color: '#b04ad8', dark: '#6a2a98', seed: 23, rot: 1.2, life: 7.8,
      desc: 'a full Steam-style game: your own OCs, custom assets, real progression', feats: TIER_FEATS(10, 3, 3, 3) } },
    { at: 27.6, fx: { kind: 'title', text: 'every tier = a real, playable game!', x: 1060, y: 40, size: 29.17, out: 3, color: '#fff6e0', life: 3.5, rot: 2, sound: 'levelup' } },
    { at: 31.15, wipe: W, sfx: 'whoosh', volume: 0.45 },
    // ---- extras
    { at: 31.7, fx: { kind: 'title', text: 'EXTRAS', sub: 'need it sooner? want more?', x: 905, y: 70, size: 66.67, life: 4.9, sound: 'fanfare_small' } },
    { at: 31.9, fx: { kind: 'rows', title: 'EXTRA-FAST DELIVERY', tag: 'per tier', color: '#ff4d6d', dark: '#c0204a', x: 905, y: 318, w: 600, rot: -1, life: 4.7, seed: 31,
      rows: [{ dot: '#3aa8e0', label: 'DUCK TIER', sub: 'delivered in 1 day', price: '+$10' }, { dot: '#ff8a2a', label: 'FOX TIER', sub: 'delivered in 2 days', price: '+$25' }, { dot: '#b04ad8', label: 'BEAR TIER', sub: 'delivered in 3 days', price: '+$35' }] } },
    { at: 33.2, fx: { kind: 'rows', title: 'EXTRA LEVEL', tag: 'any tier', color: '#4cc05a', dark: '#2a8a3a', x: 905, y: 590, w: 600, rot: 1, life: 3.4, seed: 32, rowSound: 'levelup',
      rows: [{ dot: '#ffd05a', label: '+1 LEVEL', sub: 'adds 1 day to delivery', price: '+$5' }] } },
    { at: 36.15, wipe: W, sfx: 'whoosh', volume: 0.45 },
    // ---- what you get (3D parcel)
    { at: 36.6, music: 'feast', fade: 0.4, volume: 0.5 },
    { at: 36.7, fx: { kind: 'title', text: 'WHAT YOU GET', x: 640, y: 52, size: 66.67, life: 10.2, sound: 'fanfare_small' } },
    { at: 36.8, sfx: 'egg_wobble', volume: 0.5 }, { at: 37.2, sfx: 'egg_wobble', volume: 0.5, pitch: 1.2 }, { at: 37.55, sfx: 'reveal_epic', volume: 0.6 },
    { at: 38.3, fx: { kind: 'tag', text: '3D MODELS', sub: 'characters, props, worlds', x: 240, y: 150, w: 290, h: 92, big: 36, rot: -4, seed: 41, life: 8.3, sound: 'star_pop' } },
    { at: 39.8, fx: { kind: 'tag', text: 'ANIMATED CHARACTERS', sub: 'walk, talk, dance, roar', x: 360, y: 420, w: 360, h: 92, big: 30, rot: 3, seed: 42, life: 6.8, sound: 'star_pop', pitch: 1.1 } },
    { at: 39.9, sfx: 'fox_laugh', volume: 0.4 },
    { at: 41.3, fx: { kind: 'tag', text: '2D PIXEL ART', sub: 'sprites, icons, UI', x: 640, y: 175, w: 290, h: 92, big: 36, rot: -2, seed: 43, life: 5.3, sound: 'star_pop', pitch: 1.2 } },
    { at: 42.8, fx: { kind: 'tag', text: 'SOUND + MUSIC', sub: 'made for your game', x: 1035, y: 245, w: 290, h: 92, big: 34, rot: 3, seed: 44, life: 3.8, sound: 'star_pop', pitch: 1.3 } },
    { at: 42.9, sfx: 'chip', volume: 0.4 }, { at: 43.3, sfx: 'bell', volume: 0.25 },
    { at: 44.3, fx: { kind: 'tag', text: 'SOURCE CODE', sub: 'JavaScript + Three.js', x: 1090, y: 520, w: 290, h: 92, big: 36, rot: -3, seed: 45, life: 2.3, sound: 'star_pop', pitch: 1.4 } },
    { at: 44.4, sfx: 'typing', volume: 0.45 },
    { at: 45.2, fx: { kind: 'title', text: 'IN EVERY TIER!', x: 640, y: 128, size: 45.83, color: '#ff8a8a', life: 1.4, rot: -3, sound: 'stamp' } },
    { at: 46.55, wipe: W, sfx: 'whoosh', volume: 0.45 },
    // ---- showcase: what each tier can be
    { at: 47.0, music: 'day', fade: 0.4, volume: 0.55 },
    { at: 47.1, fx: { kind: 'title', text: 'WHAT I CAN MAKE FOR YOU', x: 640, y: 78, size: 54.17, life: 2.6 } },
    { at: 47.6, fx: { kind: 'label', text: 'Sunset Shore', sub: 'a small scene, one main mechanic', x: 40, y: 600, life: 3.2 } },
    BADGE(47.9, 'DUCK TIER', '$75', '#8ad8ff'),
    { at: 47.5, notify: "one scene, one main mechanic? that's a Duck tier game.", mood: 'happy', dur: 3.2 },
    { at: 50.55, wipe: W, sfx: 'whoosh', volume: 0.45 },
    { at: 51.2, fx: { kind: 'label', text: "Mudkip's Garden", sub: 'levels, quests, characters', x: 40, y: 40, life: 3.6, tape: 'blue' } },
    BADGE(51.5, 'FOX TIER', '$150', '#ffb070'),
    { at: 51.4, notify: "levels, quests, characters, coins... that's the Fox tier!", mood: 'excited', dur: 3.3 },
    { at: 54.95, wipe: W, sfx: 'whoosh', volume: 0.45 },
    { at: 55.6, fx: { kind: 'label', text: 'The Bear Must Eat', sub: 'a full 3D tycoon game', x: 40, y: 600, life: 5.6 } },
    BADGE(55.9, 'BEAR TIER', '$350', '#e0a0ff'),
    { at: 55.8, notify: "a full game like The Bear Must Eat? that's the Bear tier.", mood: 'excited', bubble: 'excited', dur: 3.4 },
    { at: 61.15, wipe: 'rain', sfx: 'whoosh', volume: 0.45 },
    { at: 61.8, fx: { kind: 'label', text: 'Deli-very Dead', sub: 'a whole 3D town, tricks, story', x: 40, y: 600, life: 4.8, tape: 'pink' } },
    BADGE(62.0, 'BEAR TIER', '$350', '#e0a0ff'),
    { at: 61.9, notify: 'or Deli-very Dead: a whole town, bike tricks, a story. Bear tier!', mood: 'excited', dur: 3.6 },
    { at: 65.2, sfx: 'whistle', volume: 0.35 },
    { at: 66.95, fx: { kind: 'polaroid', src: '../../portfolio/media/mc-dimension.jpg', caption: 'MC mod: new dimension', x: 380, y: 70, w: 360, h: 220, rot: -6, life: 1.6, seed: 4 } },
    { at: 67.15, fx: { kind: 'polaroid', src: '../../portfolio/media/mc-mob.jpg', caption: 'MC mod: new mob', x: 800, y: 110, w: 300, h: 220, rot: 5, pos: '3% 50%', size: 'auto 100%', life: 1.4, tape: 'yellow', seed: 8 } },
    { at: 67.0, notify: '...and Minecraft mods too!', mood: 'happy', dur: 1.4 },
    { at: 68.15, wipe: W, sfx: 'whoosh', volume: 0.45 },
    { at: 68.5, unnotify: true },
    // ---- outro
    { at: 68.6, music: 'title', fade: 0.5, volume: 0.55 },
    { at: 68.8, fx: { kind: 'sign', l1: "LET'S MAKE", l2: 'YOUR GAME!', width: 430, scale: 1.15 } },
    { at: 69.2, fx: { kind: 'tag', text: '$75', sub: 'DUCK TIER', x: 268, y: 640, rot: -4, seed: 1 } },
    { at: 69.5, fx: { kind: 'tag', text: '$150', sub: 'FOX TIER', x: 640, y: 655, rot: 3, seed: 2, pitch: 1.1 } },
    { at: 69.8, fx: { kind: 'tag', text: '$350', sub: 'BEAR TIER', x: 1004, y: 645, rot: -3, seed: 3, pitch: 1.2 } },
    { at: 70.3, say: "message me on Fiverr! love y'all!", anchor: 'fox', bubble: 'excited', dur: 2.8 },
    { at: 70.8, fx: { kind: 'title', text: 'OPEN FOR ORDERS!', x: 1010, y: 120, size: 50, color: '#ff8a8a', life: 2.9, rot: 6, sound: 'stamp' } },
    { at: 73.5, wipe: 'iris', sfx: 'iris', volume: 0.5, opts: { inDur: 0.7, hold: 9, outDur: 0.2 } },
  ],
};
